import { chromium } from 'playwright';
import path from 'path';
const dir = process.cwd();
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1600, height: 1100 } });
const errors = [];
page.on('console', m => { if (m.type() === 'error' && !/ERR_CONNECTION|ERR_NAME|fonts/.test(m.text())) errors.push('console: ' + m.text()); });
page.on('pageerror', e => errors.push('pageerror: ' + e.message));
await page.goto('file://' + path.join(dir, 'index.html'));
await page.waitForTimeout(1800);
await page.selectOption('#motion', 'pickup');
await page.waitForTimeout(4000);
const a = await page.evaluate(() => document.getElementById('readout').textContent);
await page.waitForTimeout(2500);
const b = await page.evaluate(() => document.getElementById('readout').textContent);
console.log(a !== b ? 'pickup: animating' : 'pickup: NOT ANIMATING');
const box = await page.locator('canvas').boundingBox();
await page.screenshot({ path: '/tmp/vpickup.png', clip: box });
console.log(errors.length ? 'ERRORS: ' + errors.join(' | ') : 'no errors');
await browser.close();
